### PR TITLE
Enhancements to meet working with STIGViewer as well as tracking some custom metadata when converting from xccdf2inspec and inspec2ckl

### PR DESCRIPTION
**Pull request by kevin-j-smith**
#50 

https://github.com/inspec/inspec/pull/3885
https://github.com/inspec/train/pull/418

These changes yield enhancements around additional/missing information for what STIGViewer says is a valid checklist as well as add skip_message to the checklist's justification.

### CODE REVIEW

**Comment by kevin-j-smith** [comment]
CodeFactor is complaining that something that has already been fixed.   I am not sure how to over-correct the non-issue.

**Comment by aaronlippold** [comment]
Hi, I updated CodeClimate to ignore that file for now, but I do want @samcornwell and @rx294 to review the PR.

You should be able to do a force push of your PR and with the updates to the .gemspec file and CodeClimate your PR should come back clean.

Also, if we are adding new data into the processes - aka your metadata JSON file - we need to update the Docs and examples as well so we communicate it to the end users.

**Comment by aaronlippold** [comment]
@kevin-j-smith did you force push your branch?

**Comment by aaronlippold** [comment]
Did you commit an example of the metadata.json file?

**Comment by samcornwell** [comment]
@aaronlippold @kevin-j-smith checking out why this fails some tests

**Comment by aaronlippold** [comment]
https://github.com/burtlo/ohai/pull/1
https://github.com/burtlo/inspec-ohai_resource

**Comment by samcornwell** [comment]
@aaronlippold @kevin-j-smith Committed to non-master branch `mitre/fix-pr51`. Fixed bugs in that branch and then pulled into master (see #52)

**Pull request merged**
