### PR TITLE
Added logic so that inspec_tools can be a plugin to Inspec as a comma…

### LINKED ISSUE #67: Feature Enhancement: Inspec command plugin for inspec_tools
Add in the necessary logic for inspec_tools to be called from inspec as sub-command.   Inspec allows for command plugins to be registered using git urls.   It would be nice to be able to call inspec tools from the inspec command line and not have to rely on additional tools to be installed. 

inspec tools xccdf2inspec help vs inspec_tools xccdf2inspec.  

This is a minor usability feature to inline inspec_tools into inspec command line

### PR DESCRIPTION
**Pull request by kevin-j-smith**
…nd plugin

fixes #67 
closes #67 

Signed-off-by: Kevin J. Smith <kevin.j.smith2@cerner.com>

### CODE REVIEW

**Comment by kevin-j-smith** [comment]
:), it is true I copied cli.rb to plugin_cli and started the enhancement from there.  Some refactoring to remove the duplication could be done, but where to begin.

**Comment by lukemalinowski** [comment]
I like the idea, and we'll be looking into this further! 

@kevin-j-smith what do you think about dropping standalone cli support inspec_tools and making it purely an inspec plugin?

**Comment by aaronlippold** [comment]
We seem to have some CodeFactor issues.

**Comment by kevin-j-smith** [comment]
@lukemalinowski - Currently that is the only way I use it.  But I am thinking what would be better is to break out into 3 parts.   1) inspec_tools (as a pure library gem), 2) inspec_tools-bin (as the standalone cli) and 3) inspec_tools-plugin (as the Inspec plugin).

I say this because of your other tool (Heimdal) seems to be using this as a library (although I have not drilled down into that code, yet, to find out).   If it is not, then certainly as a plugin only would work.

**Comment by lukemalinowski** [comment]
I wasn't sure how to push more commits since github says you have to push commits to Kevin's branch, but there's now a new branch at https://github.com/mitre/inspec_tools/tree/kevin-j-smith-adding_inspec_command_plugin_logic which fixes the code duplication, It just assigns the base cli parser variable to be the same as the inspec plugin argument parser. 

Id appreciate it if we kept everything this on this PR, so can @kevin-j-smith apply a patch with my changes to his fork? Also, it could probably use some more testing, as I only have the rake test's, and the samples. https://stackoverflow.com/questions/28192623/create-patch-or-diff-file-from-git-repository-and-apply-it-to-another-different

**Pull request merged**
